name: "Setup Lua Environment"
description: "Build and configure Lua or LuaJIT runtime for GitHub Actions workflows"

branding:
  icon: 'code'
  color: 'purple'

inputs:
  luaVersion:
    description: "Target Lua version to install (supports 5.1, 5.2, 5.3, 5.4, luajit variants)"
    required: false
    default: "5.4"
  luaCompileFlags:
    description: "Additional compilation flags for building Lua from source"
    required: false
  buildCache:
    description: "Enable build caching to speed up subsequent runs"
    required: false
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'